def run_query_1(time_period_year,customer_state):
      sql_query_1=f"with customer_total_return as (select cr_returning_customer_sk as ctr_customer_sk ,ca_state as ctr_state, sum(cr_return_amt_inc_tax) as ctr_total_return from catalog_returns ,date_dim ,customer_address where cr_returned_date_sk = d_date_sk and d_year ={time_period_year} and cr_returning_addr_sk = ca_address_sk group by cr_returning_customer_sk ,ca_state ) select  c_customer_id,c_salutation,c_first_name,c_last_name,ca_street_number,ca_street_name ,ca_street_type,ca_suite_number,ca_city,ca_county,ca_state,ca_zip,ca_country,ca_gmt_offset ,ca_location_type,ctr_total_return from customer_total_return ctr1 ,customer_address ,customer where ctr1.ctr_total_return > (select avg(ctr_total_return)*1.2 from customer_total_return ctr2 where ctr1.ctr_state = ctr2.ctr_state) and ca_address_sk = c_current_addr_sk and ca_state = '{customer_state}' and ctr1.ctr_customer_sk = c_customer_sk order by c_customer_id,c_salutation,c_first_name,c_last_name,ca_street_number,ca_street_name ,ca_street_type,ca_suite_number,ca_city,ca_county,ca_state,ca_zip,ca_country,ca_gmt_offset ,ca_location_type,ctr_total_return limit 100;"

      return sql_query_1

def run_query_2(mid1,mid2,mid3,mid4,date,price,add_price):
  sql_query_2=f"select  i_item_id ,i_item_desc ,i_current_price from item, inventory, date_dim, store_sales where i_current_price between {price} and {add_price} and inv_item_sk = i_item_sk and d_date_sk=inv_date_sk and d_date between cast('{date}' as date) and dateadd(day,60,to_date('{date}')) and i_manufact_id in ({mid1},{mid2},{mid3},{mid4}) and inv_quantity_on_hand between 100 and 500 and ss_item_sk = i_item_sk group by i_item_id,i_item_desc,i_current_price order by i_item_id limit 100;"
  return sql_query_2


def run_query_3(return_date_1, return_date_2, return_date_3):
  
  sql_query_3=f"with sr_items as (select i_item_id item_id, sum(sr_return_quantity) sr_item_qty from store_returns, item, date_dim where sr_item_sk = i_item_sk and   d_date    in (select d_date from date_dim where d_week_seq in (select d_week_seq from date_dim where d_date in ('{return_date_1}', '{return_date_2}', '{return_date_3}'))) and   sr_returned_date_sk   = d_date_sk group by i_item_id), cr_items as (select i_item_id item_id, sum(cr_return_quantity) cr_item_qty from catalog_returns, item, date_dim where cr_item_sk = i_item_sk and   d_date    in (select d_date from date_dim where d_week_seq in (select d_week_seq from date_dim where d_date in ('{return_date_1}', '{return_date_2}',' {return_date_3}'))) and   cr_returned_date_sk   = d_date_sk group by i_item_id), wr_items as (select i_item_id item_id, sum(wr_return_quantity) wr_item_qty from web_returns, item, date_dim where wr_item_sk = i_item_sk and   d_date    in (select d_date from date_dim where d_week_seq in (select d_week_seq from date_dim where d_date in ('1998-02-20','1998-09-28','1998-11-14'))) and   wr_returned_date_sk   = d_date_sk group by i_item_id) select  sr_items.item_id ,sr_item_qty ,sr_item_qty/(sr_item_qty+cr_item_qty+wr_item_qty)/3.0 * 100 sr_dev ,cr_item_qty ,cr_item_qty/(sr_item_qty+cr_item_qty+wr_item_qty)/3.0 * 100 cr_dev ,wr_item_qty ,wr_item_qty/(sr_item_qty+cr_item_qty+wr_item_qty)/3.0 * 100 wr_dev ,(sr_item_qty+cr_item_qty+wr_item_qty)/3.0 average from sr_items ,cr_items ,wr_items where sr_items.item_id=cr_items.item_id and sr_items.item_id=wr_items.item_id order by sr_items.item_id ,sr_item_qty limit 100;"
  return sql_query_3